### ISSUE TITLE
Skills show as not being in inventory when joining someone else

### ISSUE THREAD

**Issue by DovahChikiin** [ModifAmorphic/outward#66]
After joining someone else's game, skills grey out and even after replacing them on the hotbar and the skills being bright again it says the skill is not in inventory when doing this. Happens with vanilla skills and modded skills (tested all boons, and some weapon skills like Simeon's Gambit). It also forces a restart since even after going back to your own game in singleplayer the skills are unusable. I know you are doing your best and this isn't a complaint I am so glad for your mod, its amazing and I love it, but this makes it kinda unusable for multiplayer playthroughs. <3

**Comment by ModifAmorphic** [comment]
Thanks for the report. What version of the mod were you using when you saw this? I fixed several issues in the latest release, including issues caused by loading saves after the first load.  I haven't had enough time to test this on multiplayer, outside of split screen though, so I'll have to look into it if you were on the latest (1.0.4).

**Comment by DovahChikiin** [comment]
I originally tested this on V 1.0.3, However after we saw the update today we immediately wanted to retry it and so we all updated and retried it in V 1.0.4 since I know usually a lot of fixes are done even if not listed in patch notes. We also made sure our settings matched to a T (just in case it might affect it) and the issue persists. For some reason it seems to only affect you if you are the one joining as the host is free to use the mod when we tested. We are still running the mod with "Action UI" unticked as all the other features work flawlessly as far as we can tell, the only problem is the actual hotbar.

I don't remember if I mentioned this before but if you open the skill menu and right click the skill and click "use" it is usable but when pressing the hotkey it displays the message I mentioned above.

**Comment by ModifAmorphic** [comment]
Ok, thanks.  I'll take a look and see what's going on.

**Comment by ModifAmorphic** [comment]
This should be resolved in the latest version 1.0.5 #69.
https://outward.thunderstore.io/package/ModifAmorphic/ActionUI/1.0.5/
https://github.com/ModifAmorphic/outward/releases/tag/ActionUI-v1.0.5
